### ISSUE TITLE
test 'not regenerate all subindexes' doesn't actually test that

### ISSUE THREAD

**Issue by softmoth** [Raku/Documentable#150]
The test case `'not regenerate all subindexes'` in `t/102-update.t` does not verify that unused subindexes are not regenerated.

1. Looking at [line 52](https://github.com/Raku/Documentable/blob/c3dbac82a6bd7befd1fc178934c55ec2abdc171b/t/102-update.t#L52), it saves timestamps only for the subindexes that will be changed.
2. At line 64, it verifies that all of the *changed* subindexes have a *newer* timestamp.
3. At no place does it verify that the other subindexes have the *original* timestamp.

**Comment by JJ** [comment]
:thinking:

**Comment by JJ** [comment]
Well, it's updating everything. I'm starting to think that the problem is that's it's actually testing changes *since the script was started*, which means it changed everything, instead of just the two files that were altered. But I'm not totally sure about that, and generating the cache all over takes time.

**Comment by JJ** [comment]
I drilled it down to `list-files` from `Pod::From::Cache` returning all files instead of only modified files. I really have no idea why this happens,  and it does not seem to be an actual problem otherwise. Must be the test environment...
