### ISSUE TITLE
missing three files with "setup" command

### ISSUE THREAD

**Issue by tbrowder** [Raku/Documentable#33]
**Describe the bug**
Go to the doc repo top-level directory and run:

    $ documentable setup

After the command finishes, the following files are **NOT** found:

    Makefile
    app-start
    app.pl

**To Reproduce**
Clone and install the HEAD of the master branch of module Documentable.

Run the command as shown in the problem step.

**Expected behavior**
To find the reported missing files in the doc repo at the top-level.

**Desktop (please complete the following information):**
 - OS: Debian 10 (Buster)
 - Documentable version: 1.0.9
 - Perl 6 version: This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d

**Additional context**
My clones of repos Documentable and doc are in separate directories.

**Comment by JJ** [comment]
I can't see how this would happen. That command downloads a tar file and unzips it. Here's the content
![Screenshot from 2019-09-02 19-47-47](https://user-images.githubusercontent.com/500/64129150-a6596b80-cdba-11e9-8f53-d6c2b0886b90.png)
Maybe we should check that it's been uncompressed correctly. Also I don't know why assets changes name instead of being used directly... 
I'll try and add a test for this anyway.

**Comment by tbrowder** [comment]
I see an "assets.db" file but it's an ASCII file with contents:

    (will update shortly)

**Comment by tbrowder** [comment]
By the way I tried:

    $ documentable clean

and got:

~~~
Cleaning up the directory...
rm: cannot remove 'app.pl': No such file or directory
The spawned command '    rm -rf html && rm -rf assets && rm -rf highlights \
    && rm app.pl && rm app-start && rm Makefile \
    && rm -rf template
' exited unsuccessfully (exit code: 1)
  in sub RUN-MAIN at /usr/local/rakudo.d/share/perl6/site/sources/8C56C68E804C20D14911B45EA26CF2450E29CFC8 (Documentable::CLI) line 28
  in block <unit> at /usr/local/rakudo.d/share/perl6/site/resources/1A2F2F2753AC23B9ED83E45593B48A7F719F159B line 3
  in sub MAIN at /usr/local/rakudo.d/share/perl6/site/bin/documentable line 3
  in block <unit> at /usr/local/rakudo.d/share/perl6/site/bin/documentable line 1
~~~

**Comment by tbrowder** [comment]
What's the name of the downloaded archive file?

**Comment by tbrowder** [comment]
Now it works!  But the file "assets.db" doesn't get removed with a "documentable clean."

**Comment by tbrowder** [comment]
Trying to see the docs served:

~~~
$ make run
Starting local server…
./app-start
Server available at http://127.0.0.1:3000
[2019-09-02 13:34:39.80146] [10680] [info] Copying assets...
[2019-09-02 13:34:39.80704] [10680] [info] ...done
[2019-09-02 13:34:56.42005] [10680] [debug] GET "/" (612fddc8)
[2019-09-02 13:34:56.42091] [10680] [debug] Routing to a callback
[2019-09-02 13:34:56.42119] [10680] [debug] Static file "/index.html" not found
[2019-09-02 13:34:56.42225] [10680] [debug] Template "not_found.development.html.ep" not found
[2019-09-02 13:34:56.42287] [10680] [debug] Template "not_found.html.ep" not found
[2019-09-02 13:34:56.42307] [10680] [debug] Rendering template "mojo/debug.html.ep"
[2019-09-02 13:34:56.43784] [10680] [debug] Your secret passphrase needs to be changed
[2019-09-02 13:34:56.43920] [10680] [debug] 404 Not Found (0.019168s, 52.170/s)
~~~

**Comment by antoniogamiz** [comment]
I will take a look at:

- [ ] Mojolicious passphare, ... => Though I have to say those are not important warnings, we are using the development server after all. Right now html files are served using nginx so it's not a problem.
- [ ] Fails in 'documentable clean' and assets.db not getting removed. (assets.db is an intermediate file used by sass command I think, I am not sure)

**Comment by JJ** [comment]
Mojolicious is part of perl6/doc, not this repo. And it will eventually be
replaced.

**Comment by sdondley** [comment]
I'm having the same problem. No Makefile, app-start or app.pl files. I do have type-graph.txt and documentable.json

**Comment by finanalyst** [comment]
These documentation creation problems are why I have been re-writing the system for producing documentation. It is called [Collection-raku-documentation](https://github.com/finanalyst/collection-raku-documentation.git). 

It should work out of the box by calling RakuDoc in an empty  directory.  There is a need to create a clone of this repository (but you have already done that) and to point the config file there.

I wrote the Renderer (raku-pod-render) based on the `BigFile` code. However `BigFile` died from bit rot some time ago, unless it has been revived.

Since all of the rendering of the podfiles are in templates, it should be relatively straightforward (though tedious) to create the Mode (see collection) for a single documentation file and to generate a pdf or epub file directly. I have simply not had the time yet to do this.
